name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ----------------------
  # 1. Lint & Tests
  # ----------------------
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"

      - name: Check Flutter Version
        run: flutter --version

      # Cache dependencies
      - name: Cache Flutter packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            build
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      # - name: Analyze code
      #   run: flutter analyze

      # - name: Run tests
      #   run: flutter test

  # ----------------------
  # 2. Build Artifacts
  # ----------------------
  build:
    runs-on: ubuntu-latest
    needs: test  # run only if tests pass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"

      - name: Check Flutter Version
        run: flutter --version

      # Cache dependencies
      - name: Cache Flutter packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            build
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      # --- Auto version bump ---
      - name: Update build version
        run: |
          VERSION_NAME=$(grep '^version:' pubspec.yaml | sed 's/version: //; s/+.*//')
          BUILD_NUMBER=${{ github.run_number }}
          echo "New version: $VERSION_NAME+$BUILD_NUMBER"
          sed -i "s/^version: .*/version: $VERSION_NAME+$BUILD_NUMBER/" pubspec.yaml
          cat pubspec.yaml | grep version

      # --- Android APK ---
      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # --- Web Build ---
      - name: Build Web
        run: flutter build web --release

      - name: Upload Web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
